### ISSUE TITLE
Modifiche slide

### ISSUE THREAD

**Issue by MicheleSottocasa** [GestioneProgetto/BigManager#10]
Buongiorno Prof @giodabg ,
volevo chiederle quindi cosa dovevamo modificare per la presentazione di sabato
grazie mille

**Comment by giodabg** [comment]
Scusate ma mi sono dimenticato di inviarvi i suggerimenti:
1 - aggiungere all'inizio qualche notizia sui competitor già presenti sul mercato
2 - modificare elenco funzionalità evidenziando meglio accessibilità (chi può accedere cosa) 
3 - aggiungere elementi della documentazione prodotta (una scheda con un caso d'uso significativo, almeno il diagramma dei dati con descrizione delle associazioni) 
4 - aggiungere una descrizione dell'architettura del sistema e del software utilizzato
5 - aggiungere almeno due pagine PHP significative con relativa spiegazione
6 - aggiungere almeno 2 create table significative

**Comment by MicheleSottocasa** [comment]
Scusi prof, volevo chiederle cosa intende con 2 create table significative
Vanno bene delle query al DB (ovviamente anche un po' complesse)?
