### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by giodabg** [GestioneProgetto/BigManager#6]

**Comment by giodabg** [comment]
Dalla WBS le responsabilità sono:

Andrea Occhiato: GUI relativa a Funzioni login/registr utenti
Berto Lorenzo: GUI relativa a Funzioni admin
Pugliano Denis: GUI relativa a Funzioni utente

**Comment by giodabg** [comment]
disegno dell'interfaccia grafica (immagini)

Le immagini dovrebbero essere in due versioni: bozza anche in forma di schizzo a mano libera, versione di rilascio con una grafica identica o vicina alla versione finale

**Comment by Fede04colo** [comment]
è in creazione e sarà disponibile con la documentazione finita

**Comment by giodabg** [comment]
Il documento deve descrivere l'interfaccia del prodotto finale comprensivo di TUTTE le funzionalità.
Ricordo che il documento con la GUI deve essere consistente con il documento che descrive i casi d'uso e il documento che descrive i dati.

Essendo un sito web la grafica dovrebbe essere consistente tra una pagina e l'altra per cui intestazione, menù, logo etc etc devono essere uguali

Non si capisce come fa un'utente a capire se è loggato e se è il carrello è  proprio il suo. Se il login non serve allora va tolto.
