### ISSUE TITLE
Aggiornare struttura directory GitHub

### ISSUE THREAD

**Issue by giodabg** [GestioneProgetto/BigManager#8]
La struttura tipo del repository dovrebbe essere simile a questa (versione minimale):
file Readme.md
cartella codice/code/project/htdocs/...
cartella documentazione

**Comment by Fede04colo** [comment]
ci sono i branch per la progettazione dei vari livelli, [codice  back end](/GestioneProgetto/BigManager/tree/back-end) e [codice e documentazione  front end](/GestioneProgetto/BigManager/tree/front-end), alla fine della programmazione metteremo tutto nel main

**Comment by giodabg** [comment]
La struttura nel main è già quella giusta per cui la issue può essere chiusa
